// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-LQAVYx9-7AOXtoXSRnvSFgM-8WM_diA',
    appId: '1:859958564621:web:78584e3261a2e6e0c40244',
    messagingSenderId: '859958564621',
    projectId: 'prayer-assitant-eb0c4',
    authDomain: 'prayer-assitant-eb0c4.firebaseapp.com',
    storageBucket: 'prayer-assitant-eb0c4.appspot.com',
    measurementId: 'G-7JLZ00K06W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0PwlwQRO81cZnkzxDWZDR56ADB7JfK70',
    appId: '1:859958564621:android:d030cc58f78575afc40244',
    messagingSenderId: '859958564621',
    projectId: 'prayer-assitant-eb0c4',
    storageBucket: 'prayer-assitant-eb0c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1ySXN_89dgCp5hbSOVVEGnl-qn_KIaRQ',
    appId: '1:859958564621:ios:36c120132995522ec40244',
    messagingSenderId: '859958564621',
    projectId: 'prayer-assitant-eb0c4',
    storageBucket: 'prayer-assitant-eb0c4.appspot.com',
    iosClientId: '859958564621-m7nuehshoc4rdu8nbvl90j1saal93aua.apps.googleusercontent.com',
    iosBundleId: 'com.example.prayerAssitant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1ySXN_89dgCp5hbSOVVEGnl-qn_KIaRQ',
    appId: '1:859958564621:ios:36c120132995522ec40244',
    messagingSenderId: '859958564621',
    projectId: 'prayer-assitant-eb0c4',
    storageBucket: 'prayer-assitant-eb0c4.appspot.com',
    iosClientId: '859958564621-m7nuehshoc4rdu8nbvl90j1saal93aua.apps.googleusercontent.com',
    iosBundleId: 'com.example.prayerAssitant',
  );
}
